const randomNumber = (min, max) => {
	return Math.floor(Math.random() * (max - min + 1)) + min;
};

const doWorkPromise = new Promise((resolve, reject) => {
	const numbers = [randomNumber(1, 100), randomNumber(1, 100)];
	const isOdd = randomNumber(numbers[0], numbers[1]) % 2 === 0;
	setTimeout(() => {
		if (isOdd) {
			// simulated failure
			reject('Well that was odd...');
		} else {
			// simulated success
			resolve(numbers);
		}
	}, 2000);
});

doWorkPromise
	.then((result) => {
		console.log('Success!', result);
	})
	.catch((error) => {
		console.error('Error!', error);
	});
